# Generated by Django 3.0.5 on 2020-06-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(default='default-profile-picture.jpg', upload_to=''),
        ),
    ]
